version: '3.8'

services:

  ############################
  # Dapr actor placement service
  ############################
  dapr-placement:
    image: "daprio/dapr:1.9.4"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"
  
  ############################
  # rabbitmq
  ############################
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
 
  ############################
  # Redis state store
  ############################
  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  ############################
  # seq
  ############################
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
    image: datalust/seq:latest

  ############################
  # zipkin-slim
  ############################
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"

  ############################
  # dashboard
  ############################
  dashboard:
    image: "daprio/dashboard"
    command: [ "-docker-compose=true", 
      "-components-path=/components", 
      "-config-path=/configuration/config.yaml",
      "-docker-compose-path=/docker-compose.yml"
    ]
    ports:
      - "8080:8080"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      - "./docker-compose.yml:/docker-compose.yml"

  ############################
  # SentimentScorer
  ############################
  sentimentscorer-api:
    image: ${DOCKER_REGISTRY-}sentimentscorer
    build:
      context: SentimentScorer
      dockerfile: Dockerfile
    ports:
      - "5101:80"
      - "50002:50001"
    depends_on:
      - zipkin
      - dapr-placement
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq    

  sentimentscorer-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:sentimentscorer-api"
    depends_on:
      - sentimentscorer-api      
    command: ["./daprd",
      "-app-id", "sentimentscorer-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  ############################
  # TweetProcessor
  ############################
  tweetprocessor-api:
    image: ${DOCKER_REGISTRY-}tweetprocessor    
    build:
      context: TweetProcessor
      dockerfile: Dockerfile
    ports:
      - "5102:80"
      - "50009:50001"
    depends_on:
      - redis
      - zipkin
      - dapr-placement
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq    

  tweetprocessor-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:tweetprocessor-api"
    depends_on:
      - tweetprocessor-api
    command: ["./daprd",
      "-app-id", "tweetprocessor-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  ############################
  # TweetProvider
  ############################
  tweetprovider-api:
    image: ${DOCKER_REGISTRY-}tweetprovider
    build:
      context: TweetProvider
      dockerfile: Dockerfile
    ports:
      - "5103:80"
      - "50010:50001"
    depends_on:
      - redis
      - zipkin
      - dapr-placement
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq    

  tweetprovider-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:tweetprovider-api"
    depends_on:
      - tweetprovider-api
    command: ["./daprd",
      "-app-id", "tweetprovider-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"


  ############################
  # TweetViewer
  ############################
  tweetviewer-api:
    image: ${DOCKER_REGISTRY-}tweetviewer
    build:
      context: TweetViewer
      dockerfile: Dockerfile
    ports:
      - "5104:80"
      - "50011:50001"
    depends_on:      
      - zipkin
      - dapr-placement
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq    

  tweetviewer-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:tweetviewer-api"
    depends_on:
      - tweetviewer-api
    command: ["./daprd",
      "-app-id", "tweetviewer-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

networks:
  dapr-network:
    driver: bridge
